=== gregaou/xml/complement-donnees.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT complements (complement)* >
<!ELEMENT complement (#PCDATA)>
<!ATTLIST complement ref NMTOKENS #REQUIRED>
<!ATTLIST complement node CDATA #REQUIRED>

=== gregaou/xml/complement-donnees.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE complements SYSTEM "complement-donnees.dtd">
<complements>
	<complement ref="IN18" node="siteweb">http://jean-luc.massat.perso.luminy.univ-amu.fr</complement>

	<complement ref="ENSINAU1" node="lieux">Luminy</complement>
	<complement ref="ENSINAU10" node="lieux">Luminy</complement>
	<complement ref="ENSINAU11" node="lieux">Luminy</complement>
	<complement ref="ENSINAU2" node="lieux">Luminy</complement>
	<complement ref="ENSINAU3" node="lieux">Luminy</complement>
	<complement ref="ENSINAU4" node="lieux">Luminy</complement>
	<complement ref="ENSINAU5" node="lieux">Luminy</complement>
	<complement ref="ENSINAU6" node="lieux">Luminy</complement>
	<complement ref="ENSINAU7" node="lieux">Luminy</complement>
	<complement ref="ENSINAU8" node="lieux">Luminy</complement>
	<complement ref="ENSINAU9" node="lieux">Luminy</complement>
	<complement ref="ENSINBU1" node="lieux">Luminy</complement>
	<complement ref="ENSINBU10" node="lieux">Luminy</complement>
	<complement ref="ENSINBU11" node="lieux">Luminy</complement>
	<complement ref="ENSINBU12" node="lieux">Luminy</complement>
	<complement ref="ENSINBU13" node="lieux">Luminy</complement>
	<complement ref="ENSINBU14" node="lieux">Luminy</complement>
	<complement ref="ENSINBU2" node="lieux">Luminy</complement>
	<complement ref="ENSINBU3" node="lieux">Luminy</complement>
	<complement ref="ENSINBU4" node="lieux">Luminy</complement>
	<complement ref="ENSINBU5" node="lieux">Luminy</complement>
	<complement ref="ENSINBU6" node="lieux">Luminy</complement>
	<complement ref="ENSINBU7" node="lieux">Luminy</complement>
	<complement ref="ENSINBU8" node="lieux">Luminy</complement>
	<complement ref="ENSINBU9" node="lieux">Luminy</complement>
	<complement ref="ENSINCU1" node="lieux">Luminy</complement>
	<complement ref="ENSINCU10" node="lieux">Luminy</complement>
	<complement ref="ENSINCU11" node="lieux">Luminy</complement>
	<complement ref="ENSINCU12" node="lieux">Luminy</complement>
	<complement ref="ENSINCU13" node="lieux">Luminy</complement>
	<complement ref="ENSINCU14" node="lieux">Luminy</complement>
	<complement ref="ENSINCU15" node="lieux">Luminy</complement>
	<complement ref="ENSINCU16" node="lieux">Luminy</complement>
	<complement ref="ENSINCU17" node="lieux">Luminy</complement>
	<complement ref="ENSINCU18" node="lieux">Luminy</complement>
	<complement ref="ENSINCU19" node="lieux">Luminy</complement>
	<complement ref="ENSINCU2" node="lieux">Luminy</complement>
	<complement ref="ENSINCU20" node="lieux">Luminy</complement>
	<complement ref="ENSINCU21" node="lieux">Luminy</complement>
	<complement ref="ENSINCU22" node="lieux">Luminy</complement>
	<complement ref="ENSINCU23" node="lieux">Luminy</complement>
	<complement ref="ENSINCU24" node="lieux">Luminy</complement>
	<complement ref="ENSINCU25" node="lieux">Luminy</complement>
	<complement ref="ENSINCU26" node="lieux">Luminy</complement>
	<complement ref="ENSINCU27" node="lieux">Luminy</complement>
	<complement ref="ENSINCU28" node="lieux">Luminy</complement>
	<complement ref="ENSINCU29" node="lieux">Luminy</complement>
	<complement ref="ENSINCU3" node="lieux">Luminy</complement>
	<complement ref="ENSINCU30" node="lieux">Luminy</complement>
	<complement ref="ENSINCU31" node="lieux">Luminy</complement>
	<complement ref="ENSINCU32" node="lieux">Luminy</complement>
	<complement ref="ENSINCU33" node="lieux">Luminy</complement>
	<complement ref="ENSINCU34" node="lieux">Luminy</complement>
	<complement ref="ENSINCU35" node="lieux">Luminy</complement>
	<complement ref="ENSINCU36" node="lieux">Luminy</complement>
	<complement ref="ENSINCU37" node="lieux">Luminy</complement>
	<complement ref="ENSINCU38" node="lieux">Luminy</complement>
	<complement ref="ENSINCU39" node="lieux">Luminy</complement>
	<complement ref="ENSINCU4" node="lieux">Luminy</complement>
	<complement ref="ENSINCU40" node="lieux">Luminy</complement>
	<complement ref="ENSINCU41" node="lieux">Luminy</complement>
	<complement ref="ENSINCU42" node="lieux">Luminy</complement>
	<complement ref="ENSINCU43" node="lieux">Luminy</complement>
	<complement ref="ENSINCU44" node="lieux">Luminy</complement>
	<complement ref="ENSINCU45" node="lieux">Luminy</complement>
	<complement ref="ENSINCU46" node="lieux">Luminy</complement>
	<complement ref="ENSINCU47" node="lieux">Luminy</complement>
	<complement ref="ENSINCU48" node="lieux">Luminy</complement>
	<complement ref="ENSINCU49" node="lieux">Luminy</complement>
	<complement ref="ENSINCU5" node="lieux">Luminy</complement>
	<complement ref="ENSINCU50" node="lieux">Luminy</complement>
	<complement ref="ENSINCU51" node="lieux">Luminy</complement>
	<complement ref="ENSINCU52" node="lieux">Luminy</complement>
	<complement ref="ENSINCU53" node="lieux">Luminy</complement>
	<complement ref="ENSINCU54" node="lieux">Luminy</complement>
	<complement ref="ENSINCU55" node="lieux">Luminy</complement>
	<complement ref="ENSINCU56" node="lieux">Luminy</complement>
	<complement ref="ENSINCU57" node="lieux">Luminy</complement>
	<complement ref="ENSINCU58" node="lieux">Luminy</complement>
	<complement ref="ENSINCU59" node="lieux">Luminy</complement>
	<complement ref="ENSINCU6" node="lieux">Luminy</complement>
	<complement ref="ENSINCU60" node="lieux">Luminy</complement>
	<complement ref="ENSINCU61" node="lieux">Luminy</complement>
	<complement ref="ENSINCU62" node="lieux">Luminy</complement>
	<complement ref="ENSINCU63" node="lieux">Luminy</complement>
	<complement ref="ENSINCU64" node="lieux">Luminy</complement>
	<complement ref="ENSINCU65" node="lieux">Luminy</complement>
	<complement ref="ENSINCU66" node="lieux">Luminy</complement>
	<complement ref="ENSINCU67" node="lieux">Luminy</complement>
	<complement ref="ENSINCU7" node="lieux">Luminy</complement>
	<complement ref="ENSINCU8" node="lieux">Luminy</complement>
	<complement ref="ENSINCU9" node="lieux">Luminy</complement>
	<complement ref="ENSINDU1" node="lieux">Luminy</complement>
	<complement ref="ENSINDU2" node="lieux">Luminy</complement>
	<complement ref="ENSINDU3" node="lieux">Luminy</complement>
	<complement ref="ENSINDU4" node="lieux">Luminy</complement>
	<complement ref="ENSISCU1" node="lieux">Luminy</complement>
	<complement ref="ENSISCU2" node="lieux">Luminy</complement>
	<complement ref="ENSISCU20" node="lieux">Luminy</complement>
	<complement ref="ENSISCU21" node="lieux">Luminy</complement>
	<complement ref="ENSISCU22" node="lieux">Luminy</complement>
	<complement ref="ENSISCU23" node="lieux">Luminy</complement>
	<complement ref="ENSISCU24" node="lieux">Luminy</complement>
	<complement ref="ENSISCU25" node="lieux">Luminy</complement>
	<complement ref="ENSISCU26" node="lieux">Luminy</complement>
	<complement ref="ENSISCU27" node="lieux">Luminy</complement>
	<complement ref="ENSISCU28" node="lieux">Luminy</complement>
	<complement ref="ENSISCU29" node="lieux">Luminy</complement>
	<complement ref="ENSISCU3" node="lieux">Luminy</complement>
	<complement ref="ENSISCU30" node="lieux">Luminy</complement>
	<complement ref="ENSISCU31" node="lieux">Luminy</complement>
	<complement ref="ENSISCU32" node="lieux">Luminy</complement>
	<complement ref="ENSISCU33" node="lieux">Luminy</complement>
	<complement ref="ENSISCU34" node="lieux">Luminy</complement>
	<complement ref="ENSISCU35" node="lieux">Luminy</complement>
	<complement ref="ENSISCU36" node="lieux">Luminy</complement>
	<complement ref="ENSISCU37" node="lieux">Luminy</complement>
	<complement ref="ENSISCU38" node="lieux">Luminy</complement>
	<complement ref="ENSISCU39" node="lieux">Luminy</complement>
	<complement ref="ENSISCU4" node="lieux">Luminy</complement>
	<complement ref="ENSISCU40" node="lieux">Luminy</complement>
	<complement ref="ENSISCU41" node="lieux">Luminy</complement>
	<complement ref="ENSISCU42" node="lieux">Luminy</complement>
	<complement ref="ENSISCU43" node="lieux">Luminy</complement>
	<complement ref="ENSISCU44" node="lieux">Luminy</complement>
	<complement ref="ENSISCU45" node="lieux">Luminy</complement>
	<complement ref="ENSISCU46" node="lieux">Luminy</complement>
	<complement ref="ENSISCU5" node="lieux">Luminy</complement>
	<complement ref="ENSISCU55" node="lieux">Luminy</complement>
	<complement ref="ENSISCU6" node="lieux">Luminy</complement>
	<complement ref="ENSISCU7" node="lieux">Luminy</complement>
	<complement ref="ENSISCU8" node="lieux">Luminy</complement>
	<complement ref="ENSISDU3" node="lieux">Luminy</complement>
	<complement ref="ENSISDU4" node="lieux">Luminy</complement>

	<complement ref="PRSIN5B1" node="lieux">Luminy</complement>
	<complement ref="PRSIN5B2" node="lieux">Luminy</complement>
	<complement ref="PRSIN5B3" node="lieux">Luminy</complement>
	<complement ref="PRSIN5C1" node="lieux">Luminy</complement>
	<complement ref="PRSIN5C2" node="lieux">Luminy</complement>
	<complement ref="PRSIN5E1" node="lieux">Luminy</complement>
	<complement ref="PRSIN5E2" node="lieux">Luminy</complement>
	<complement ref="PRSIN4T0" node="lieux">Luminy</complement>
	<complement ref="PRSIN5A0" node="lieux">Luminy</complement>
	<complement ref="PRSIN5D0" node="lieux">Luminy</complement>
	<complement ref="PRSIN5F0" node="lieux">Luminy</complement>
	<complement ref="PRSIN5G0" node="lieux">Luminy</complement>

	<complement ref="PRSIN5B1" node="debouches">Enseignants, Chercheurs et experts, chef de projets R&amp;D, Informaticiens et Automaticien spécialistes : en diagnostic et surveillance des systèmes complexes, en Imagerie numérique, en informatique fondamentale et appliquée, en sciences de l'information.</complement>
	<complement ref="PRSIN5B2" node="debouches">Enseignants, Chercheurs et experts, chef de projets R&amp;D, Informaticiens et Automaticien spécialistes : en diagnostic et surveillance des systèmes complexes, en Imagerie numérique, en informatique fondamentale et appliquée, en sciences de l'information.</complement>
